config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :cuisines
  resources :recipe_categories
  resources :shop_franchises

  resources :products do
  	resources :product_nutritions, controller: 'nutrition'
    resources :product_shops
    resources :product_in_shop_franchises
  end

  get '/products/:id/shop_availability', to: 'products#show_shop_availability'

  resources :recipes do
  	resources :recipe_steps
  	resources :recipe_ingredients
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
	has_many :recipes, :class_name => "Recipe", :foreign_key => "cuisine_id"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :parent, :class_name => "Product", :foreign_key => "product_id", optional: true
  has_many :child_products, :class_name => "Product", :foreign_key => "product_id"
  has_one :product_nutrition
  has_one :product_shop
  has_many :product_in_shop_franchise, :class_name => "ProductInShopFranchise", :foreign_key => "product_id"
  has_many :recipe_ingredients, :class_name => "RecipeIngredient", :foreign_key => "product_id"
  has_many :recipes, :class_name => "Recipe", :foreign_key => "product_id"
end

app/models/product_nutrition.rb
class ProductNutrition < ApplicationRecord
  belongs_to :product
end

app/models/product_shop.rb
class ProductShop < ApplicationRecord
	belongs_to :product
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :cuisine, optional: true
  belongs_to :recipe_category, optional: true
  has_many :recipe_steps
  has_many :recipe_ingredients
end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord
	has_many :recipes, :class_name => "Recipe", :foreign_key => "recipe_category_id"
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe, :foreign_key => "recipe_id"
  belongs_to :product, :foreign_key => "product_id"
end

app/models/recipe_step.rb
class RecipeStep < ApplicationRecord
  belongs_to :recipe
end

app/models/shop_franchise.rb
class ShopFranchise < ApplicationRecord
	has_many :product_in_shop_franchise, :class_name => "ProductInShopFranchise", :foreign_key => "shop_franchise"
end

app/controllers/recipe_categories_controller.rb
class RecipeCategoriesController < ApplicationController

	def index
		@categories = RecipeCategory.all
	end

	def show
		@category = RecipeCategory.find(params[:id])
		@recipes = @category.recipes.all
	end

	def new
		@category = RecipeCategory.new
	end

	def create
		@category = RecipeCategory.new(category_params)

		if @category.save
			redirect_to @category
		else
			render 'new'
		end
	end

	def edit
		@category = RecipeCategory.find(params[:id])
	end

	def update
		@category = RecipeCategory.find(params[:id])

		if @category.update(category_params)
			redirect_to @category
		else
			render 'edit'
		end
	end

	def destroy
		@category = RecipeCategory.find(params[:id])
		@category.destroy
		
		redirect_to recipe_categories_path
	end

	private
	def category_params
		params.require(:recipe_category).permit(:name)
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	def index
		@recipes = Recipe.all
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
		fix_assocs @recipe

		if @recipe.save
			redirect_to @recipe
		else
			render 'new'
		end
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])
		fix_assocs @recipe

		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy
		
		redirect_to recipes_path
	end

	private
	def recipe_params
		params.require(:recipe).permit(:name, :description, :image, :cooking_method, :preperation_time, :cooking_time, :amount_of_servings)
	end

	def fix_assocs recipe
		associate_cuisine recipe
		associate_product recipe
		associate_category recipe
	end

	def associate_cuisine recipe
		if (params['recipe']['cuisine'].length > 0)
			cuisine_id = params['recipe']['cuisine'].to_i
			product = Cuisine.find(cuisine_id)

			recipe.cuisine = product
		end
	end

	def associate_product recipe
		if (params['recipe']['product'].length > 0)
			product_id = params['recipe']['product'].to_i
			product = Product.find(product_id)

			recipe.product = product
		end
	end

	def associate_category recipe
		if (params['recipe']['recipe_category'].length > 0)
			category_id = params['recipe']['recipe_category'].to_i
			category = RecipeCategory.find(category_id)

			recipe.recipe_category = category
		end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/nutrition_helper.rb
module NutritionHelper
end

app/helpers/product_shops_helper.rb
module ProductShopsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recipe_categories_helper.rb
module RecipeCategoriesHelper
end

app/helpers/recipe_steps_helper.rb
module RecipeStepsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shop_franchises_helper.rb
module ShopFranchisesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/recipe_categories/_form.html.erb
<%= form_for @category do |f| %>
 
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/recipe_categories/edit.html.erb
<h1>Edit Category</h1>
<%= render 'form' %>
<%= link_to 'Back', recipe_categories_path %>

app/views/recipe_categories/index.html.erb
<h1>Categories</h1>

<%= link_to 'New category', new_recipe_category_path %>

<table>
  <tr>
    <th>Category name</th>
    <th></th>
  </tr>
 
  <% @categories.each do |article| %>
    <tr>
      <td><%= article.name %></td>
      <td><%= link_to 'Show details', recipe_category_path(article) %></td>
      <td><%= link_to 'Edit', edit_recipe_category_path(article) %></td>
      <td><%= link_to 'Destroy', recipe_category_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/recipe_categories/new.html.erb
<h1>New Category</h1>
<%= render 'form' %>
<%= link_to 'Back', recipe_categories_path %>

app/views/recipe_categories/show.html.erb
<p>
  <strong>Id:</strong>
  <%= @category.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<h2>Recipes in this category</h2>
<ul>
<% @recipes.each do |recipe| %>
<li><%= link_to recipe.name, recipe %></li>
<% end %>
</ul>

<%= link_to 'Edit', edit_recipe_category_path(@category) %> |
<%= link_to 'Back', recipe_categories_path %>