config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :cuisines
  resources :recipe_categories
  resources :shop_franchises

  resources :products do
  	resources :product_nutritions, controller: 'nutrition'
    resources :product_shops
    resources :product_in_shop_franchises
  end

  get '/products/:id/shop_availability', to: 'products#show_shop_availability'

  resources :recipes do
  	resources :recipe_steps
  	resources :recipe_ingredients
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
	has_many :recipes, :class_name => "Recipe", :foreign_key => "cuisine_id"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :parent, :class_name => "Product", :foreign_key => "product_id", optional: true
  has_many :child_products, :class_name => "Product", :foreign_key => "product_id"
  has_one :product_nutrition
  has_one :product_shop
  has_many :product_in_shop_franchise, :class_name => "ProductInShopFranchise", :foreign_key => "product_id"
  has_many :recipe_ingredients, :class_name => "RecipeIngredient", :foreign_key => "product_id"
  has_many :recipes, :class_name => "Recipe", :foreign_key => "product_id"
end

app/models/product_nutrition.rb
class ProductNutrition < ApplicationRecord
  belongs_to :product
end

app/models/product_shop.rb
class ProductShop < ApplicationRecord
	belongs_to :product
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :cuisine, optional: true
  belongs_to :recipe_category, optional: true
  has_many :recipe_steps
  has_many :recipe_ingredients
end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord
	has_many :recipes, :class_name => "Recipe", :foreign_key => "recipe_category_id"
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe, :foreign_key => "recipe_id"
  belongs_to :product, :foreign_key => "product_id"
end

app/models/recipe_step.rb
class RecipeStep < ApplicationRecord
  belongs_to :recipe
end

app/models/shop_franchise.rb
class ShopFranchise < ApplicationRecord
	has_many :product_in_shop_franchise, :class_name => "ProductInShopFranchise", :foreign_key => "shop_franchise"
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController

	def index
		@cuisines = Cuisine.all
	end

	def show
		@cuisine = Cuisine.find(params[:id])
		@recipes = @cuisine.recipes.all
	end

	def new
		@cuisine = Cuisine.new
	end

	def create
		@cuisine = Cuisine.new(cuisine_params)

		if @cuisine.save
			redirect_to @cuisine
		else
			render 'new'
		end
	end

	def edit
		@cuisine = Cuisine.find(params[:id])
	end

	def update
		@cuisine = Cuisine.find(params[:id])

		if @cuisine.update(cuisine_params)
			redirect_to @cuisine
		else
			render 'edit'
		end
	end

	def destroy
		@cuisine = Cuisine.find(params[:id])
		@cuisine.destroy
		
		redirect_to cuisines_path
	end

	private
	def cuisine_params
		params.require(:cuisine).permit(:name)
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
		@nutrition = @product.product_nutrition
		@shop_info = @product.product_shop
		@product_in_shop = ProductInShopFranchise.new

		recipe_usages = @product.recipe_ingredients.all
		@recipes = []
		recipe_usages.each do |item|
			@recipes.push(item.recipe)
		end

		@creating_recipes = @product.recipes

		@children = @product.child_products.all

	end

	def show_shop_availability
		@product = Product.find(params[:id])
		@product_in_shop = ProductInShopFranchise.new
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		set_product_parent @product

		if @product.save
			redirect_to @product
		else
			render 'new'
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		set_product_parent @product

		if @product.update(product_params)
			redirect_to @product
		else
			render 'edit'
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		
		redirect_to products_path
	end

	private
	def product_params
		params.require(:product).permit(:name)
	end

	def set_product_parent product
		if (params['product']['parent'].length > 0)
			parent_id = params['product']['parent'].to_i

			parent = Product.find_by_id(parent_id)

			if !(parent.nil?)
				product.parent = parent
			end
		end
	end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	def index
		@recipes = Recipe.all
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
		fix_assocs @recipe

		if @recipe.save
			redirect_to @recipe
		else
			render 'new'
		end
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])
		fix_assocs @recipe

		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy
		
		redirect_to recipes_path
	end

	private
	def recipe_params
		params.require(:recipe).permit(:name, :description, :image, :cooking_method, :preperation_time, :cooking_time, :amount_of_servings)
	end

	def fix_assocs recipe
		associate_cuisine recipe
		associate_product recipe
		associate_category recipe
	end

	def associate_cuisine recipe
		if (params['recipe']['cuisine'].length > 0)
			cuisine_id = params['recipe']['cuisine'].to_i
			product = Cuisine.find(cuisine_id)

			recipe.cuisine = product
		end
	end

	def associate_product recipe
		if (params['recipe']['product'].length > 0)
			product_id = params['recipe']['product'].to_i
			product = Product.find(product_id)

			recipe.product = product
		end
	end

	def associate_category recipe
		if (params['recipe']['recipe_category'].length > 0)
			category_id = params['recipe']['recipe_category'].to_i
			category = RecipeCategory.find(category_id)

			recipe.recipe_category = category
		end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/nutrition_helper.rb
module NutritionHelper
end

app/helpers/product_shops_helper.rb
module ProductShopsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recipe_steps_helper.rb
module RecipeStepsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shop_franchises_helper.rb
module ShopFranchisesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cuisines/_form.html.erb
<%= form_for @cuisine do |f| %>
 
  <% if @cuisine.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@cuisine.errors.count, "error") %> prohibited
        this cuisine from being saved:
      </h2>
      <ul>
        <% @cuisine.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/cuisines/edit.html.erb
<h1>Edit Cuisine</h1>
<%= render 'form' %>
<%= link_to 'Back', cuisines_path %>

app/views/cuisines/index.html.erb
<h1>Cuisines</h1>

<%= link_to 'New cuisine', new_cuisine_path %>

<table>
  <tr>
    <th>Cuisine name</th>
    <th></th>
  </tr>
 
  <% @cuisines.each do |article| %>
    <tr>
      <td><%= article.name %></td>
      <td><%= link_to 'Show details', cuisine_path(article) %></td>
      <td><%= link_to 'Edit', edit_cuisine_path(article) %></td>
      <td><%= link_to 'Destroy', cuisine_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/cuisines/new.html.erb
<h1>New Cuisine</h1>
<%= render 'form' %>
<%= link_to 'Back', cuisines_path %>

app/views/cuisines/show.html.erb
<p>
  <strong>Id:</strong>
  <%= @cuisine.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cuisine.name %>
</p>

<h2>Recipes in this cuisine</h2>
<ul>
<% @recipes.each do |recipe| %>
<li><%= link_to recipe.name, recipe %></li>
<% end %>
</ul>

<%= link_to 'Edit', edit_cuisine_path(@cuisine) %> |
<%= link_to 'Back', cuisines_path %>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
 
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this product from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :parent %><br>
    <%= f.number_field :parent %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% if (!(@product.new_record?) && !(@product.parent.nil?)) %>
<script type="text/javascript"> // Dirty workaround, but it works ;)
  $("#product_parent").val('<%= @product.parent.id %>');
</script>
<% end %>

<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render 'form' %>
<%= link_to 'Back', product_path(@product) %>

app/views/products/index.html.erb
<h1>Products</h1>

<%= link_to 'New product', new_product_path %>

<table>
  <tr>
    <th>Product name</th>
    <th></th>
  </tr>
 
  <% @products.each do |article| %>
    <tr>
      <td><%= article.name %></td>
      <td><%= link_to 'Show details', product_path(article) %></td>
      <td><%= link_to 'Edit', edit_product_path(article) %></td>
      <td><%= link_to 'Destroy', product_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Id:</strong>
  <%= @product.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
 
<p>
  <strong>More generic product:</strong>
  <%=
  if !(@product.parent.nil?)
  	link_to @product.parent.name, product_path(@product.parent)
  else
  	"no more generic product"
  end
  %>
</p>

<h2>Recipes that make this product</h2>
<ul>
<%
  @creating_recipes.each do |recipe|
%>

<li>
<%=
  link_to recipe.name, recipe
%>
</li>

<%  
  end
%>
</ul>


<h2>Recipes that use this product</h2>
<ul>
<%
  @recipes.each do |recipe|
%>

<li>
<%=
  link_to recipe.name, recipe
%>
</li>

<%  
  end
%>
</ul>

<h2>More specific products</h2>
<ul>
<%
  @children.each do |child|
%>

<li>
<%=
  link_to child.name, child
%>
</li>

<%  
  end
%>
</ul>


<hr>

<%=
if (@nutrition.nil?)
  link_to 'Add nutritional information', new_product_product_nutrition_path(@product)
else
  link_to 'View nutritional information', product_product_nutritions_path(@product)
end
%> |
<%=
if (@shop_info.nil?)
  link_to 'Add shop information', new_product_product_shop_path(@product)
else
  link_to 'View shop information', product_product_shops_path(@product)
end
%> |
<%= link_to 'Check shop availability', product_path(@product) + '/shop_availability' %> |
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/show_shop_availability.html.erb
<h2>Shop availability for <%= @product.name %></h2>
<%= render @product.product_in_shop_franchise %>

<h3>Add shop availability</h3>
<%= render 'product_in_shop_franchises/form' %>


<%= link_to 'Back', product_path(@product) %>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
 
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@recipe.errors.count, "error") %> prohibited
        this recipe from being saved:
      </h2>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </p>

  <p>
    <%= f.label :product %><br>
    <%= f.number_field :product %>
  </p>

  <p>
    <%= f.label :cuisine %><br>
    <%= f.number_field :cuisine %>
  </p>

  <p>
    <%= f.label :recipe_category %><br>
    <%= f.number_field :recipe_category %>
  </p>

  <p>
    <%= f.label :cooking_method %><br>
    <%= f.text_field :cooking_method %>
  </p>

  <p>
    <%= f.label :preperation_time %><br>
    <%= f.text_field :preperation_time %>
  </p>

  <p>
    <%= f.label :cooking_time %><br>
    <%= f.text_field :cooking_time %>
  </p>

  <p>
    <%= f.label :amount_of_servings %><br>
    <%= f.text_field :amount_of_servings %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render 'form' %>
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<%= link_to 'New recipe', new_recipe_path %>

<table>
  <tr>
    <th>Recipe name</th>
    <th>Cooking method</th>
    <th>Preperation time</th>
    <th>Cooking time</th>
    <th>Amount of servings</th>
  </tr>
 
  <% @recipes.each do |article| %>
    <tr>
      <td><%= article.name %></td>
      <td><%= article.cooking_method %></td>
      <td><%= article.preperation_time %></td>
      <td><%= article.cooking_time %></td>
      <td><%= article.amount_of_servings %></td>
      <td><%= link_to 'Show details', recipe_path(article) %></td>
      <td><%= link_to 'Edit', edit_recipe_path(article) %></td>
      <td><%= link_to 'Destroy', recipe_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render 'form' %>
<%= link_to 'Back', cuisines_path %>

app/views/recipes/show.html.erb
<h2>
  <%= @recipe.name %>
</h2>

<p>
  <strong>Id:</strong>
  <%= @recipe.id %>
</p>

<% if @recipe.image %>
  <div style="width: 100%; text-align: center;">
    <img src="<%= @recipe.image %>">
  </div>
  <% end %>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%=
  if !(@recipe.cuisine.nil?)
    link_to @recipe.cuisine.name, cuisine_path(@recipe.cuisine)
  else
    "no cuisine selected"
  end
  %>
</p>

<p>
  <strong>Category:</strong>
  <%=
  if !(@recipe.recipe_category.nil?)
    link_to @recipe.recipe_category.name, recipe_category_path(@recipe.recipe_category)
  else
    "no category selected"
  end
  %>
</p>

<p>
  <strong>Final product:</strong>
  <%=
  if !(@recipe.product.nil?)
    link_to @recipe.product.name, product_path(@recipe.cuisine)
  else
    "no final product selected"
  end
  %>
</p>

<p>
  <strong>Cooking method:</strong>
  <%= @recipe.cooking_method %>
</p>

<p>
  <strong>Preperation time:</strong>
  <%= @recipe.preperation_time %>
</p>

<p>
  <strong>Cooking time:</strong>
  <%= @recipe.cooking_time %>
</p>

<p>
  <strong>Amount of servings:</strong>
  <%= @recipe.amount_of_servings %>
</p>


<h2>Ingredients</h2>
<ul>
  <%= render @recipe.recipe_ingredients %>
</ul>

<h2>How to make it</h2>
<ol>
  <%= render @recipe.recipe_steps.order('step_number ASC') %>
</ol>


<%= link_to 'Add ingredient', new_recipe_recipe_ingredient_path(@recipe) %> |
<%= link_to 'Add step', new_recipe_recipe_step_path(@recipe) %> |
<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>