config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :cuisines
  resources :recipe_categories
  resources :shop_franchises

  resources :products do
  	resources :product_nutritions, controller: 'nutrition'
    resources :product_shops
    resources :product_in_shop_franchises
  end

  get '/products/:id/shop_availability', to: 'products#show_shop_availability'

  resources :recipes do
  	resources :recipe_steps
  	resources :recipe_ingredients
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
	has_many :recipes, :class_name => "Recipe", :foreign_key => "cuisine_id"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :parent, :class_name => "Product", :foreign_key => "product_id", optional: true
  has_many :child_products, :class_name => "Product", :foreign_key => "product_id"
  has_one :product_nutrition
  has_one :product_shop
  has_many :product_in_shop_franchise, :class_name => "ProductInShopFranchise", :foreign_key => "product_id"
  has_many :recipe_ingredients, :class_name => "RecipeIngredient", :foreign_key => "product_id"
  has_many :recipes, :class_name => "Recipe", :foreign_key => "product_id"
end

app/models/product_nutrition.rb
class ProductNutrition < ApplicationRecord
  belongs_to :product
end

app/models/product_shop.rb
class ProductShop < ApplicationRecord
	belongs_to :product
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :cuisine, optional: true
  belongs_to :recipe_category, optional: true
  has_many :recipe_steps
  has_many :recipe_ingredients
end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord
	has_many :recipes, :class_name => "Recipe", :foreign_key => "recipe_category_id"
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe, :foreign_key => "recipe_id"
  belongs_to :product, :foreign_key => "product_id"
end

app/models/recipe_step.rb
class RecipeStep < ApplicationRecord
  belongs_to :recipe
end

app/models/shop_franchise.rb
class ShopFranchise < ApplicationRecord
	has_many :product_in_shop_franchise, :class_name => "ProductInShopFranchise", :foreign_key => "shop_franchise"
end

app/controllers/nutrition_controller.rb
class NutritionController < ApplicationController

	def index
		@product = Product.find(params[:product_id])
		@nutrition = @product.product_nutrition

		if @nutrition.nil?
			raise ActionController::RoutingError.new('No nutritional information found')
		end
	end

	def new
		@product = Product.find(params[:product_id])
		@nutrition = ProductNutrition.new
	end

	def create
		@product = Product.find(params[:product_id])
		@nutrition = ProductNutrition.new(nutrition_params)
		@nutrition.product = @product

		if @nutrition.save
			redirect_to @product
		else
			render 'new'
		end
	end

	def edit
		@product = Product.find(params[:product_id])
		@nutrition = ProductNutrition.find(params[:id])
	end

	def update
		@product = Product.find(params[:product_id])
		@nutrition = ProductNutrition.find(params[:id])

		if @product.update(product_params)
			redirect_to @product
		else
			render 'edit'
		end
	end

	def destroy
		@product = Product.find(params[:product_id])
		@nutrition = ProductNutrition.find(params[:id])
		
		@nutrition.destroy

		redirect_to product_path @product
	end

	private
	def nutrition_params
		params.require(:product_nutrition).permit(:calories, :fats, :saturated_fats, :carbohydrates, :sugars, :fiber, :proteins, :salt, :vitamin_a, :vitamin_b1, :vitamin_b2, :vitamin_b3, :vitamin_b5, :vitamin_b6, :vitamin_b7, :vitamin_b9, :vitamin_b12, :vitamin_c, :vitamin_d, :vitamin_e, :vitamin_k, :nutrition_per, :nutrition_per_unit)
	end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	def index
		@recipes = Recipe.all
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
		fix_assocs @recipe

		if @recipe.save
			redirect_to @recipe
		else
			render 'new'
		end
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])
		fix_assocs @recipe

		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy
		
		redirect_to recipes_path
	end

	private
	def recipe_params
		params.require(:recipe).permit(:name, :description, :image, :cooking_method, :preperation_time, :cooking_time, :amount_of_servings)
	end

	def fix_assocs recipe
		associate_cuisine recipe
		associate_product recipe
		associate_category recipe
	end

	def associate_cuisine recipe
		if (params['recipe']['cuisine'].length > 0)
			cuisine_id = params['recipe']['cuisine'].to_i
			product = Cuisine.find(cuisine_id)

			recipe.cuisine = product
		end
	end

	def associate_product recipe
		if (params['recipe']['product'].length > 0)
			product_id = params['recipe']['product'].to_i
			product = Product.find(product_id)

			recipe.product = product
		end
	end

	def associate_category recipe
		if (params['recipe']['recipe_category'].length > 0)
			category_id = params['recipe']['recipe_category'].to_i
			category = RecipeCategory.find(category_id)

			recipe.recipe_category = category
		end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/nutrition_helper.rb
module NutritionHelper
end

app/helpers/product_shops_helper.rb
module ProductShopsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recipe_steps_helper.rb
module RecipeStepsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shop_franchises_helper.rb
module ShopFranchisesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/nutrition/_form.html.erb
<%= form_for([@product, @nutrition]) do |f| %>
 
  <% if @nutrition.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@nutrition.errors.count, "error") %> prohibited
        this cuisine from being saved:
      </h2>
      <ul>
        <% @nutrition.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :calories %><br>
    <%= f.number_field :calories %>
  </p>
 
  <p>
    <%= f.label :fats %><br>
    <%= f.text_field :fats %>
  </p>
 
  <p>
    <%= f.label :saturated_fats %><br>
    <%= f.text_field :saturated_fats %>
  </p>
 
  <p>
    <%= f.label :carbohydrates %><br>
    <%= f.text_field :carbohydrates %>
  </p>
 
  <p>
    <%= f.label :sugars %><br>
    <%= f.text_field :sugars %>
  </p>
 
  <p>
    <%= f.label :fiber %><br>
    <%= f.text_field :fiber %>
  </p>
 
  <p>
    <%= f.label :proteins %><br>
    <%= f.text_field :proteins %>
  </p>
 
  <p>
    <%= f.label :salt %><br>
    <%= f.text_field :salt %>
  </p>
 
  <p>
    <%= f.label :vitamin_a %><br>
    <%= f.text_field :vitamin_a %>
  </p>
 
  <p>
    <%= f.label :vitamin_b1 %><br>
    <%= f.text_field :vitamin_b1 %>
  </p>
 
  <p>
    <%= f.label :vitamin_b2 %><br>
    <%= f.text_field :vitamin_b2 %>
  </p>
 
  <p>
    <%= f.label :vitamin_b3 %><br>
    <%= f.text_field :vitamin_b3 %>
  </p>
 
  <p>
    <%= f.label :vitamin_b5 %><br>
    <%= f.text_field :vitamin_b5 %>
  </p>
 
  <p>
    <%= f.label :vitamin_b6 %><br>
    <%= f.text_field :vitamin_b6 %>
  </p>
 
  <p>
    <%= f.label :vitamin_b7 %><br>
    <%= f.text_field :vitamin_b7 %>
  </p>
 
  <p>
    <%= f.label :vitamin_b9 %><br>
    <%= f.text_field :vitamin_b9 %>
  </p>
 
  <p>
    <%= f.label :vitamin_b12 %><br>
    <%= f.text_field :vitamin_b12 %>
  </p>
 
  <p>
    <%= f.label :vitamin_c %><br>
    <%= f.text_field :vitamin_c %>
  </p>
 
  <p>
    <%= f.label :vitamin_d %><br>
    <%= f.text_field :vitamin_d %>
  </p>
 
  <p>
    <%= f.label :vitamin_e %><br>
    <%= f.text_field :vitamin_e %>
  </p>
 
  <p>
    <%= f.label :vitamin_k %><br>
    <%= f.text_field :vitamin_k %>
  </p>
 
  <p>
    <%= f.label :nutrition_per %><br>
    <%= f.text_field :nutrition_per %>
  </p>
 
  <p>
    <%= f.label :nutrition_per_unit %><br>
    <%= f.text_field :nutrition_per_unit %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/nutrition/edit.html.erb
<h1>Edit Product Nutritional information of &quot;<%= @product.name %>&quot;</h1>
<%= render 'form' %>
<%= link_to 'Back', product_path(@product) %>

app/views/nutrition/index.html.erb
<h1>Nutritional information for product <%= @product.name %> </h1>

<p>
  <strong>Id:</strong>
  <%= @nutrition.id %>
</p>

<p>
  <strong>Nutritional information per:</strong>
  <%= @nutrition.nutrition_per %> 
  <%= @nutrition.nutrition_per_unit %> 
</p>

<table>
		<tr><td>Calories</td> <td><%= @nutrition.calories %></td></tr>
		<tr><td>Fats</td> <td><%= @nutrition.fats %></td></tr>
		<tr><td>Saturated fats</td> <td><%= @nutrition.saturated_fats %></td></tr>
		<tr><td>Carbohydrates</td> <td><%= @nutrition.carbohydrates %></td></tr>
		<tr><td>Sugars</td> <td><%= @nutrition.sugars %></td></tr>
		<tr><td>Fiber</td> <td><%= @nutrition.fiber %></td></tr>
		<tr><td>Salt</td> <td><%= @nutrition.salt %></td></tr>
		<tr><td>Vitamin A</td> <td><%= @nutrition.vitamin_a %></td></tr>
		<tr><td>Vitamin B1</td> <td><%= @nutrition.vitamin_b1 %></td></tr>
		<tr><td>Vitamin B2</td> <td><%= @nutrition.vitamin_b2 %></td></tr>
		<tr><td>Vitamin B3</td> <td><%= @nutrition.vitamin_b3 %></td></tr>
		<tr><td>Vitamin B5</td> <td><%= @nutrition.vitamin_b5 %></td></tr>
		<tr><td>Vitamin B6</td> <td><%= @nutrition.vitamin_b6 %></td></tr>
		<tr><td>Vitamin B7</td> <td><%= @nutrition.vitamin_b7 %></td></tr>
		<tr><td>Vitamin B9</td> <td><%= @nutrition.vitamin_b9 %></td></tr>
		<tr><td>Vitamin B12</td> <td><%= @nutrition.vitamin_b12 %></td></tr>
		<tr><td>Vitamin C</td> <td><%= @nutrition.vitamin_c %></td></tr>
		<tr><td>Vitamin D</td> <td><%= @nutrition.vitamin_d %></td></tr>
		<tr><td>Vitamin E</td> <td><%= @nutrition.vitamin_e %></td></tr>
		<tr><td>Vitamin K</td> <td><%= @nutrition.vitamin_k %></td></tr>
</table>

<%= link_to 'Edit', edit_product_product_nutrition_path(@product, @nutrition) %> |

<%= link_to 'Destroy', product_product_nutrition_path(@product, @nutrition),
              method: :delete,
              data: { confirm: 'Are you sure?' } %> |

<%= link_to 'Back', product_path(@product) %>

app/views/nutrition/new.html.erb
<h1>Add Product Nutritional information for &quot;<%= @product.name %>&quot;</h1>
<%= render 'form' %>
<%= link_to 'Back', product_path(@product) %>