config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :cuisines
  resources :recipe_categories
  resources :shop_franchises

  resources :products do
  	resources :product_nutritions, controller: 'nutrition'
    resources :product_shops
    resources :product_in_shop_franchises
  end

  get '/products/:id/shop_availability', to: 'products#show_shop_availability'

  resources :recipes do
  	resources :recipe_steps
  	resources :recipe_ingredients
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
	has_many :recipes, :class_name => "Recipe", :foreign_key => "cuisine_id"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :parent, :class_name => "Product", :foreign_key => "product_id", optional: true
  has_many :child_products, :class_name => "Product", :foreign_key => "product_id"
  has_one :product_nutrition
  has_one :product_shop
  has_many :product_in_shop_franchise, :class_name => "ProductInShopFranchise", :foreign_key => "product_id"
  has_many :recipe_ingredients, :class_name => "RecipeIngredient", :foreign_key => "product_id"
  has_many :recipes, :class_name => "Recipe", :foreign_key => "product_id"
end

app/models/product_nutrition.rb
class ProductNutrition < ApplicationRecord
  belongs_to :product
end

app/models/product_shop.rb
class ProductShop < ApplicationRecord
	belongs_to :product
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :cuisine, optional: true
  belongs_to :recipe_category, optional: true
  has_many :recipe_steps
  has_many :recipe_ingredients
end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord
	has_many :recipes, :class_name => "Recipe", :foreign_key => "recipe_category_id"
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe, :foreign_key => "recipe_id"
  belongs_to :product, :foreign_key => "product_id"
end

app/models/recipe_step.rb
class RecipeStep < ApplicationRecord
  belongs_to :recipe
end

app/models/shop_franchise.rb
class ShopFranchise < ApplicationRecord
	has_many :product_in_shop_franchise, :class_name => "ProductInShopFranchise", :foreign_key => "shop_franchise"
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController

	def index
		@cuisines = Cuisine.all
	end

	def show
		@cuisine = Cuisine.find(params[:id])
		@recipes = @cuisine.recipes.all
	end

	def new
		@cuisine = Cuisine.new
	end

	def create
		@cuisine = Cuisine.new(cuisine_params)

		if @cuisine.save
			redirect_to @cuisine
		else
			render 'new'
		end
	end

	def edit
		@cuisine = Cuisine.find(params[:id])
	end

	def update
		@cuisine = Cuisine.find(params[:id])

		if @cuisine.update(cuisine_params)
			redirect_to @cuisine
		else
			render 'edit'
		end
	end

	def destroy
		@cuisine = Cuisine.find(params[:id])
		@cuisine.destroy
		
		redirect_to cuisines_path
	end

	private
	def cuisine_params
		params.require(:cuisine).permit(:name)
	end

end

app/controllers/product_shops_controller.rb
class ProductShopsController < ApplicationController

	def index
		@product = Product.find(params[:product_id])
		@info_shop = @product.product_shop

		if @info_shop.nil?
			raise ActionController::RoutingError.new('No shop information found for product')
		end
	end

	def new
		@product = Product.find(params[:product_id])
		@info_shop = ProductShop.new
	end

	def create
		@product = Product.find(params[:product_id])
		@info_shop = ProductShop.new(shop_params)
		@info_shop.product = @product

		if @info_shop.save
			redirect_to @product
		else
			render 'new'
		end
	end

	def edit
		@product = Product.find(params[:product_id])
		@info_shop = ProductShop.find(params[:id])
	end

	def update
		@product = Product.find(params[:product_id])
		@info_shop = ProductShop.find(params[:id])

		if @info_shop.update(shop_params)
			redirect_to @product
		else
			render 'edit'
		end
	end

	def destroy
		@product = Product.find(params[:product_id])
		@info_shop = ProductShop.find(params[:id])
		
		@info_shop.destroy

		redirect_to product_path @product
	end

	private
	def shop_params
		params.require(:product_shop).permit(:barcode, :amount, :amount_unit)
	end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	def index
		@recipes = Recipe.all
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
		fix_assocs @recipe

		if @recipe.save
			redirect_to @recipe
		else
			render 'new'
		end
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])
		fix_assocs @recipe

		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy
		
		redirect_to recipes_path
	end

	private
	def recipe_params
		params.require(:recipe).permit(:name, :description, :image, :cooking_method, :preperation_time, :cooking_time, :amount_of_servings)
	end

	def fix_assocs recipe
		associate_cuisine recipe
		associate_product recipe
		associate_category recipe
	end

	def associate_cuisine recipe
		if (params['recipe']['cuisine'].length > 0)
			cuisine_id = params['recipe']['cuisine'].to_i
			product = Cuisine.find(cuisine_id)

			recipe.cuisine = product
		end
	end

	def associate_product recipe
		if (params['recipe']['product'].length > 0)
			product_id = params['recipe']['product'].to_i
			product = Product.find(product_id)

			recipe.product = product
		end
	end

	def associate_category recipe
		if (params['recipe']['recipe_category'].length > 0)
			category_id = params['recipe']['recipe_category'].to_i
			category = RecipeCategory.find(category_id)

			recipe.recipe_category = category
		end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/nutrition_helper.rb
module NutritionHelper
end

app/helpers/product_shops_helper.rb
module ProductShopsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recipe_steps_helper.rb
module RecipeStepsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shop_franchises_helper.rb
module ShopFranchisesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/product_shops/_form.html.erb
<%= form_for([@product, @info_shop]) do |f| %>
 
  <% if @info_shop.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@info_shop.errors.count, "error") %> prohibited
        this cuisine from being saved:
      </h2>
      <ul>
        <% @info_shop.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :barcode %><br>
    <%= f.text_field :barcode %>
  </p>
 
  <p>
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </p>
 
  <p>
    <%= f.label :amount_unit %><br>
    <%= f.text_field :amount_unit %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/product_shops/edit.html.erb
<h1>Edit shop information for product &quot;<%= @product.name %>&quot;</h1>
<%= render 'form' %>
<%= link_to 'Back', product_path(@product) %>

app/views/product_shops/index.html.erb
<h1>Shop information for product <%= @product.name %> </h1>

<p>
  <strong>Id:</strong>
  <%= @info_shop.id %>
</p>

<table>
		<tr><td>Barcode</td> <td><%= @info_shop.barcode %></td></tr>
		<tr><td>Amount</td> <td><%= @info_shop.amount %> <%= @info_shop.amount_unit %></td></tr>
</table>

<%= link_to 'Edit', edit_product_product_shop_path(@product, @info_shop) %> |

<%= link_to 'Destroy', product_product_shop_path(@product, @info_shop),
              method: :delete,
              data: { confirm: 'Are you sure?' } %> |

<%= link_to 'Back', product_path(@product) %>

app/views/product_shops/new.html.erb
<h1>Add shop information for product &quot;<%= @product.name %>&quot;</h1>
<%= render 'form' %>
<%= link_to 'Back', product_path(@product) %>